apiVersion: apps/v1
kind: Deployment
metadata:
  name: emejia
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: emejia
  template:
    metadata:
      labels:
        app: emejia
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions: [{ key: app, operator: In, values: [emejia] }]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: emejia-from
        image: emejia-jdk16:0.0.1
        ports:
          - name: http
            containerPort: 7082
      terminationGracePeriodSeconds: 1
