apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpy-sonarqube
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions: [{ key: app, operator: In, values: [devops] }]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: sonarqube-container
        image: sonarqube:latest
        ports:
          - name: port3
            containerPort: 9092
      terminationGracePeriodSeconds: 1
