apiVersion: v1
kind: Service
metadata:
  name: scv-jenkins
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - protocol: TCP
      nodePort: 30392
      port: 8080
      targetPort: port1
    - protocol: TCP
      nodePort: 30393
      port: 5000
      targetPort: port2