apiVersion: v1
kind: Service
metadata:
  name: scv-sonarqube
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - protocol: TCP
      nodePort: 30450
      port: 9000
      targetPort: http
    - protocol: TCP
      nodePort: 30460
      port: 9092
      targetPort: http